#!/usr/bin/env Rscript
options(stringsAsFactors=FALSE); options(timeout=300)
suppressPackageStartupMessages({library(ggplot2);library(dplyr);library(tibble);library(readr);library(showtext);library(sysfonts);library(scales);library(patchwork)})
source(file.path("R", "load_config.R"))
ARIAL=A4OL_FONT_FILE; if(!file.exists(ARIAL))stop("Arial.ttf not found"); font_add("Arial",ARIAL); showtext_auto(); showtext_opts(dpi=300)
ROOT=file.path(A4OL_FIGURE_ROOT,"SCENIC_A4OL_FORMAL_V9"); OUT=file.path(ROOT,"SCENIC_EGR1_downstream_all","plots"); TAB=file.path(ROOT,"SCENIC_EGR1_downstream_all","tables"); dir.create(OUT,recursive=TRUE,showWarnings=FALSE); dir.create(TAB,recursive=TRUE,showWarnings=FALSE)
COL_A4="#D19246"; COL_O="#71A682"; COL_C="#C43C39"; TOP=25
check=function(f){if(!file.exists(f))stop("File not found: ",f)}
safe_w=function(x,g)tryCatch({if(length(unique(g))<2)return(NA_real_); wilcox.test(x~g)$p.value},error=function(e)NA_real_)
rescale_safe=function(x,to=c(5,14)){if(length(x)==0)return(numeric(0)); if(all(is.na(x)))return(rep(mean(to),length(x))); r=range(x,na.rm=TRUE); if(!all(is.finite(r))||diff(r)==0)return(rep(mean(to),length(x))); scales::rescale(x,to=to,from=r)}
prep=function(expr,cell){if("cell"%in%colnames(cell))rownames(cell)=cell$cell; common=intersect(colnames(expr),rownames(cell)); list(expr=expr[,common,drop=FALSE],cell=cell[common,,drop=FALSE])}
group_col=function(cell){h=c("A4_status","a4_status","group","Group"); h=h[h%in%colnames(cell)]; if(length(h)==0)stop("No A4 status col"); h[1]}
targets=function(regs,name,tf){if(!name%in%names(regs))stop("Regulon not found: ",name); setdiff(unique(as.character(regs[[name]])),tf)}
stats=function(expr,cell,genes){gcol=group_col(cell); g=as.character(cell[[gcol]]); keep=which(g%in%c("Other OLs","A4-OLs")); expr=expr[,keep,drop=FALSE]; g=g[keep]; genes=intersect(genes,rownames(expr)); if(length(genes)==0)stop("No genes overlap"); mat=expr[genes,,drop=FALSE]; io=which(g=="Other OLs"); ia=which(g=="A4-OLs"); mo=rowMeans(mat[,io,drop=FALSE],na.rm=TRUE); ma=rowMeans(mat[,ia,drop=FALSE],na.rm=TRUE); pv=apply(mat,1,function(v)safe_w(v,factor(g,levels=c("Other OLs","A4-OLs")))); tibble(gene=genes,mean_other=mo,mean_a4=ma,delta=ma-mo,abs_delta=abs(ma-mo),p_value=pv,p_adj=p.adjust(pv,"BH"),direction=case_when(delta>0~"A4-up",delta<0~"Other-up",TRUE~"Neutral"))%>%arrange(desc(abs_delta),p_adj,gene)}
layout_nodes=function(df,tf){df=df[seq_len(min(TOP,nrow(df))),]; n=nrow(df); ang=seq(pi/2,pi/2-2*pi+2*pi/n,length.out=n); df=df%>%mutate(x=1.05*cos(ang),y=1.05*sin(ang),label_x=1.42*cos(ang),label_y=1.42*sin(ang),hjust=ifelse(cos(ang)>=0,0,1)); list(df=df,edges=data.frame(x=0,y=0,xend=df$x,yend=df$y))}
makep=function(st,tf,title,table){df=st[seq_len(min(TOP,nrow(st))),]; write_csv(df,table); L=layout_nodes(df,tf); d=L$df; e=L$edges; d$direction=factor(d$direction,levels=c("A4-up","Other-up","Neutral")); ggplot()+geom_segment(data=e,aes(x=x,y=y,xend=xend,yend=yend),color="#C8C8C8",linewidth=.55)+geom_segment(data=d,aes(x=x,y=y,xend=label_x,yend=label_y),color="#D4D4D4",linewidth=.35)+geom_point(data=d,aes(x=x,y=y,size=abs_delta,fill=direction),shape=21,color="white",stroke=.8,alpha=.96)+geom_point(aes(x=0,y=0),size=9.6,shape=21,fill=COL_C,color="white",stroke=1.2)+annotate("text",x=0,y=0,label=tf,family="Arial",fontface="bold",size=7.8,color="white")+geom_text(data=d,aes(x=label_x,y=label_y,label=gene,hjust=hjust),family="Arial",size=4.6)+scale_fill_manual(values=c("A4-up"=COL_A4,"Other-up"=COL_O,"Neutral"="#CFCFCF"),drop=FALSE)+scale_size_continuous(name="|Mean expression delta|",range=c(6,16))+coord_equal(xlim=c(-1.75,1.75),ylim=c(-1.55,1.55),clip="off")+labs(title=title,subtitle="Top 25 targets ranked by |mean expression delta|")+theme_void(base_family="Arial")+theme(plot.title=element_text(size=18,face="bold",hjust=.5),plot.subtitle=element_text(size=10.5,hjust=.5),legend.position="right",legend.title=element_text(size=11,face="bold"),legend.text=element_text(size=10))}
files=c(file.path(ROOT,"human/SCENIC/int/2.6_regulons_asGeneSet.Rds"),file.path(ROOT,"mouse/SCENIC/int/2.6_regulons_asGeneSet.Rds"),file.path(ROOT,"human/rds/human_exprMat_log2_counts.rds"),file.path(ROOT,"mouse/rds/mouse_exprMat_log2_counts.rds"),file.path(ROOT,"human/rds/human_cellInfo.rds"),file.path(ROOT,"mouse/rds/mouse_cellInfo.rds")); invisible(lapply(files,check))
hr=readRDS(files[1]); mr=readRDS(files[2]); he=readRDS(files[3]); me=readRDS(files[4]); hc=as.data.frame(readRDS(files[5])); mc=as.data.frame(readRDS(files[6])); H=prep(he,hc); M=prep(me,mc)
hcore=stats(H$expr,H$cell,targets(hr,"EGR1","EGR1")); hext=stats(H$expr,H$cell,targets(hr,"EGR1_extended","EGR1")); mcore=stats(M$expr,M$cell,targets(mr,"Egr1","Egr1")); mext=stats(M$expr,M$cell,targets(mr,"Egr1_extended","Egr1"))
write_csv(hcore,file.path(TAB,"Network_Human_EGR1_core_all_target_stats.csv")); write_csv(hext,file.path(TAB,"Network_Human_EGR1_extended_all_target_stats.csv")); write_csv(mcore,file.path(TAB,"Network_Mouse_Egr1_core_all_target_stats.csv")); write_csv(mext,file.path(TAB,"Network_Mouse_Egr1_extended_all_target_stats.csv"))
p1=makep(hcore,"EGR1","Human EGR1 core regulon targets",file.path(TAB,"Network_Human_EGR1_core_top25_targets_beautified.csv")); p2=makep(hext,"EGR1","Human EGR1 extended regulon targets",file.path(TAB,"Network_Human_EGR1_extended_top25_targets_beautified.csv")); p3=makep(mcore,"Egr1","Mouse Egr1 core regulon targets",file.path(TAB,"Network_Mouse_Egr1_core_top25_targets_beautified.csv")); p4=makep(mext,"Egr1","Mouse Egr1 extended regulon targets",file.path(TAB,"Network_Mouse_Egr1_extended_top25_targets_beautified.csv"))
save=function(p,n){ggsave(file.path(OUT,paste0(n,".png")),p,width=10,height=8,dpi=300,bg="white"); ggsave(file.path(OUT,paste0(n,".pdf")),p,width=10,height=8,bg="white")}
save(p1,"Network_Human_EGR1_core_top25_targets_beautified"); save(p2,"Network_Human_EGR1_extended_top25_targets_beautified"); save(p3,"Network_Mouse_EGR1_core_top25_targets_beautified"); save(p4,"Network_Mouse_EGR1_extended_top25_targets_beautified"); save(p1,"Network_Human_EGR1_core_top25_targets")
comb=((p1+p2)/(p3+p4))+plot_layout(guides="collect")+plot_annotation(title="Cross-species EGR1/Egr1 regulon target networks",theme=theme(text=element_text(family="Arial"),plot.title=element_text(size=20,face="bold",hjust=.5)))&theme(legend.position="right")
ggsave(file.path(OUT,"Network_Human_Mouse_EGR1_Egr1_top25_targets_2x2_combined_beautified.png"),comb,width=18,height=15,dpi=300,bg="white"); ggsave(file.path(OUT,"Network_Human_Mouse_EGR1_Egr1_top25_targets_2x2_combined_beautified.pdf"),comb,width=18,height=15,bg="white")
