#!/usr/bin/env Rscript
options(stringsAsFactors=FALSE); options(timeout=300)
suppressPackageStartupMessages({library(ggplot2);library(dplyr);library(stringr);library(showtext);library(sysfonts);library(grid)})
source(file.path("R", "load_config.R"))
ARIAL=A4OL_FONT_FILE; if(!file.exists(ARIAL))stop("Arial not found"); font_add("arial",ARIAL); showtext_auto(); showtext_opts(dpi=300)
ROOT=file.path(A4OL_FIGURE_ROOT,"SCENIC_A4OL_FORMAL_V9","SCENIC_EGR1_downstream_all"); ENR=file.path(ROOT,"enrichment"); PLOT=file.path(ROOT,"plots"); TAB=file.path(ROOT,"tables"); dir.create(PLOT,recursive=TRUE,showWarnings=FALSE); dir.create(TAB,recursive=TRUE,showWarnings=FALSE)
find1=function(x){h=x[file.exists(x)]; if(length(h)==0)NA_character_ else h[1]}
readgo=function(file,sp){df=read.csv(file,check.names=FALSE); cn=colnames(df); l=tolower(cn); get=function(cand){i=which(l%in%tolower(cand)); if(length(i)==0)NA_character_ else cn[i[1]]}; desc=get(c("Description","Term","description")); padj=get(c("p.adjust","padj","FDR","qvalue")); count=get(c("Count","count")); if(is.na(desc)||is.na(padj))stop("Bad GO table: ",file); out=df%>%mutate(Species=sp,Description_use=.data[[desc]],p_adjust_use=as.numeric(.data[[padj]])); out$Count_use=if(!is.na(count))as.numeric(out[[count]])else NA_real_; out%>%filter(!is.na(Description_use),!is.na(p_adjust_use),p_adjust_use>0)%>%mutate(log10p=-log10(p_adjust_use),database="GO",Description_wrap=str_wrap(Description_use,42))%>%arrange(p_adjust_use,desc(log10p),desc(Count_use))}
br=function(x){x=x[is.finite(x)&!is.na(x)]; if(length(x)==0)return(c(0,10)); seq(0,max(10,ceiling(max(x)/10)*10),by=10)}
plotgo=function(df,sp,prefix){pd=df%>%slice_head(n=15)%>%arrange(log10p)%>%mutate(Description_wrap=factor(Description_wrap,levels=unique(Description_wrap)),p_color=log10p); b=br(pd$p_color); write.csv(pd,file.path(TAB,paste0(prefix,"_plot_data_log10padj.csv")),row.names=FALSE); p=ggplot(pd,aes(log10p,Description_wrap))+geom_vline(xintercept=0,linetype="dashed",color="grey60",linewidth=.6)+geom_col(aes(fill=Species),width=.62,alpha=.85)+geom_point(aes(size=Count_use,color=p_color,shape=database),stroke=.6,fill=NA)+scale_fill_manual(values=c("Human"="#E64B35","Mouse"="#4DBBD5"))+scale_color_gradient(low="#FFD700",high="#2E8B57",name=expression(-log[10](p.adjust)),breaks=b,labels=function(x)as.integer(x),limits=c(0,max(b)),guide=guide_colorbar(title.position="top",barheight=unit(7.2,"cm"),barwidth=unit(.55,"cm"),label.position="right",title.theme=element_text(family="arial",size=36,face="bold"),label.theme=element_text(family="arial",size=28)))+scale_shape_manual(values=c("GO"=16),name="Database")+scale_size_continuous(name="Gene count",range=c(4,13))+labs(x=expression(-log[10](padj)),y=NULL,title=paste0("GO BP enrichment: ",sp," EGR1 extended targets"))+theme_minimal(base_family="arial")+theme(axis.text=element_text(size=42,color="black"),axis.title.x=element_text(size=46,face="bold"),plot.title=element_text(size=48,face="bold",hjust=.5),legend.text=element_text(size=40),legend.title=element_text(size=40,face="bold"),panel.grid.major.y=element_blank(),panel.grid.minor=element_blank())+guides(fill=guide_legend(title="Species"),shape="none",size=guide_legend(override.aes=list(shape=16))); ggsave(file.path(PLOT,paste0(prefix,".png")),p,width=24,height=16,dpi=300,bg="white"); ggsave(file.path(PLOT,paste0(prefix,".pdf")),p,width=24,height=16,bg="white")}
hf=find1(c(file.path(ENR,"Human_EGR1_extended_targets_GO_BP.csv"),file.path(ENR,"GO_BP_Human_EGR1_extended_targets.csv"),file.path(TAB,"Human_EGR1_extended_targets_GO_BP.csv"))); mf=find1(c(file.path(ENR,"Mouse_EGR1_extended_targets_GO_BP.csv"),file.path(ENR,"GO_BP_Mouse_EGR1_extended_targets.csv"),file.path(TAB,"Mouse_EGR1_extended_targets_GO_BP.csv"))); if(is.na(hf)||is.na(mf))stop("GO table not found")
plotgo(readgo(hf,"Human"),"Human","GO_BP_Human_EGR1_extended_targets"); plotgo(readgo(mf,"Mouse"),"Mouse","GO_BP_Mouse_EGR1_extended_targets")
