#!/usr/bin/env Rscript
options(stringsAsFactors=FALSE); options(timeout=300)
suppressPackageStartupMessages({library(ggplot2);library(dplyr);library(showtext);library(sysfonts)})
source(file.path("R", "load_config.R"))
ARIAL=A4OL_FONT_FILE; if(!file.exists(ARIAL))stop("Arial not found"); font_add("arial",ARIAL); showtext_auto(); showtext_opts(dpi=300)
ROOT=file.path(A4OL_FIGURE_ROOT,"SCENIC_A4OL_FORMAL_V9"); OUT=file.path(ROOT,"SCENIC_EGR1_downstream_all","plots_redraw"); TAB=file.path(ROOT,"SCENIC_EGR1_downstream_all","tables_redraw"); dir.create(OUT,recursive=TRUE,showWarnings=FALSE); dir.create(TAB,recursive=TRUE,showWarnings=FALSE)
auc=as.matrix(readRDS(file.path(ROOT,"human/rds/human_auc_matrix.rds"))); cell=as.data.frame(readRDS(file.path(ROOT,"human/rds/human_cellInfo.rds"))); cell$cell=rownames(cell)
detect=function(df,cand){h=cand[cand%in%colnames(df)]; if(length(h)==0)NA_character_ else h[1]}
a4=detect(cell,c("A4_status","a4_status","A4_group","group")); apo=detect(cell,c("apoe_group","APOE","apoe_genotype","genotype_use","genotype")); if(is.na(a4)||is.na(apo))stop("Cannot detect A4/APOE columns")
common=intersect(colnames(auc),cell$cell); auc=auc[,common,drop=FALSE]; cell=filter(cell,cell%in%common)
core=grep("^EGR1 \\(",rownames(auc),value=TRUE)[1]; ext=grep("^EGR1_extended \\(",rownames(auc),value=TRUE)[1]
recode=function(x){x=toupper(as.character(x)); out=rep(NA_character_,length(x)); out[grepl("APOE3|E3|3",x)&!grepl("4",x)]="APOE3"; out[grepl("APOE4|E4|4",x)]="APOE4"; out}
mk=function(reg,label){data.frame(cell=colnames(auc),regulon_AUC=as.numeric(auc[reg,]))%>%left_join(cell,by="cell")%>%transmute(cell,regulon_AUC,A4_status=as.character(.data[[a4]]),APOE_group=recode(.data[[apo]]),regulon_label=label)%>%filter(A4_status%in%c("Other OLs","A4-OLs"),APOE_group%in%c("APOE3","APOE4"),is.finite(regulon_AUC))%>%mutate(A4_status=factor(A4_status,levels=c("Other OLs","A4-OLs")),APOE_group=factor(APOE_group,levels=c("APOE3","APOE4")))}
star=function(p){if(is.na(p))"ns" else if(p<1e-4)"****" else if(p<1e-3)"***" else if(p<1e-2)"**" else if(p<.05)"*" else "ns"}
sig=function(df){df%>%group_by(A4_status,regulon_label)%>%summarise(p_value=tryCatch(wilcox.test(regulon_AUC~APOE_group)$p.value,error=function(e)NA_real_),y_max=max(regulon_AUC),y_min=min(regulon_AUC),.groups="drop")%>%mutate(sig_label=sapply(p_value,star),yr=pmax(y_max-y_min,y_max+1e-4),y_bracket=y_max+.08*yr,y_tick=y_max+.04*yr,y_text=ifelse(sig_label=="ns",y_max+.155*yr,y_max+.115*yr),x1=1,x2=2,xm=1.5)}
plot_one=function(df,title,out){sg=sig(df); write.csv(df,file.path(TAB,paste0(out,"_plot_data.csv")),row.names=FALSE); write.csv(sg,file.path(TAB,paste0(out,"_sig.csv")),row.names=FALSE); ymax=max(c(df$regulon_AUC,sg$y_text)); p=ggplot(df,aes(APOE_group,regulon_AUC))+geom_violin(aes(fill=APOE_group,color=APOE_group),width=.8,alpha=.18,linewidth=.55,trim=TRUE)+geom_jitter(aes(color=APOE_group),width=.13,size=.55,alpha=.3,stroke=0)+geom_boxplot(aes(fill=APOE_group,color=APOE_group),width=.2,outlier.shape=NA,alpha=.65,linewidth=.5)+facet_wrap(~A4_status,nrow=1)+geom_segment(data=sg,aes(x=x1,xend=x2,y=y_bracket,yend=y_bracket),inherit.aes=FALSE,linewidth=.45)+geom_segment(data=sg,aes(x=x1,xend=x1,y=y_tick,yend=y_bracket),inherit.aes=FALSE,linewidth=.45)+geom_segment(data=sg,aes(x=x2,xend=x2,y=y_tick,yend=y_bracket),inherit.aes=FALSE,linewidth=.45)+geom_text(data=sg,aes(x=xm,y=y_text,label=sig_label),inherit.aes=FALSE,family="arial",size=3.9)+scale_fill_manual(values=c("APOE3"="#67C1DF","APOE4"="#F05A3A"))+scale_color_manual(values=c("APOE3"="#67C1DF","APOE4"="#F05A3A"))+coord_cartesian(ylim=c(0,ymax*1.08),clip="off")+labs(title=title,x=NULL,y="Regulon AUC")+theme_classic(base_family="arial",base_size=11)+theme(plot.title=element_text(size=15,face="bold",hjust=.5),axis.text.x=element_text(size=10,angle=35,hjust=1),axis.text.y=element_text(size=10),axis.title.y=element_text(size=13),strip.background=element_rect(fill="grey92",color="grey65",linewidth=.6),strip.text=element_text(size=11,face="bold"),legend.position="top",legend.title=element_blank(),legend.text=element_text(size=11),panel.border=element_rect(color="black",fill=NA,linewidth=.55),panel.grid=element_blank()); ggsave(file.path(OUT,paste0(out,".png")),p,width=7.2,height=4.4,dpi=300,bg="white"); ggsave(file.path(OUT,paste0(out,".pdf")),p,width=7.2,height=4.4,bg="white")}
plot_one(mk(core,"EGR1 core regulon"),"Human EGR1 core regulon activity stratified by APOE genotype","Human_EGR1_core_regulon_AUC_APOE3_vs_APOE4_stratified_sig_paper_style")
plot_one(mk(ext,"EGR1 extended regulon"),"Human EGR1 extended regulon activity stratified by APOE genotype","Human_EGR1_extended_regulon_AUC_APOE3_vs_APOE4_stratified_sig_paper_style")
