#!/usr/bin/env Rscript
options(stringsAsFactors=FALSE); options(timeout=300)
suppressPackageStartupMessages({library(ggplot2);library(dplyr);library(tidyr);library(ggrepel);library(sysfonts);library(showtext)})
source(file.path("R", "load_config.R"))
ARIAL_TTF=A4OL_FONT_FILE; if(!file.exists(ARIAL_TTF))stop("Arial font file not found")
font_add("Arial",ARIAL_TTF); showtext_auto(); showtext_opts(dpi=300); PLOT_FONT="Arial"
ROOT=file.path(A4OL_FIGURE_ROOT,"SCENIC_A4OL_FORMAL_V9"); OUT=file.path(ROOT,"SCENIC_EGR1_visualization_all"); PLOT=file.path(OUT,"plots"); TAB=file.path(OUT,"tables"); dir.create(PLOT,recursive=TRUE,showWarnings=FALSE); dir.create(TAB,recursive=TRUE,showWarnings=FALSE)
hfile=file.path(ROOT,"human/tables/human_all_regulon_AUC_A4_vs_Other_stats.csv"); mfile=file.path(ROOT,"mouse/tables/mouse_all_regulon_AUC_A4_vs_Other_stats.csv")
strip_tf=function(x){gsub("\\s*\\(.*\\)$","",gsub("_extended","",x))}; rtype=function(x)ifelse(grepl("_extended",x),"extended","core"); neg=function(p){p=as.numeric(p); p[is.na(p)]=1; -log10(pmax(p,.Machine$double.xmin))}
h=read.csv(hfile,check.names=FALSE); m=read.csv(mfile,check.names=FALSE); if(!"TF"%in%colnames(h))h$TF=strip_tf(h$regulon); if(!"TF"%in%colnames(m))m$TF=strip_tf(m$regulon); if(!"TF_upper"%in%colnames(h))h$TF_upper=toupper(h$TF); if(!"TF_upper"%in%colnames(m))m$TF_upper=toupper(m$TF)
df=bind_rows(mutate(h,species="Human"),mutate(m,species="Mouse"))%>%mutate(species=factor(species,levels=c("Human","Mouse")),TF_show=TF,TF_upper=toupper(TF_upper),regulon_type=rtype(regulon),plot_fdr=pmax(ifelse(is.na(wilcox_fdr),1,wilcox_fdr),.Machine$double.xmin),neglog10_fdr=pmin(neg(plot_fdr),300),direction_group=case_when(wilcox_fdr<.05 & delta_mean_A4_minus_other>0~"A4-up",wilcox_fdr<.05 & delta_mean_A4_minus_other<0~"Other-up",TRUE~"NS"),direction_group=factor(direction_group,levels=c("A4-up","NS","Other-up")),is_EGR1=TF_upper=="EGR1")
pick=function(d,sp,dir){x=d%>%filter(species==sp,direction_group==dir)%>%group_by(species,TF_upper)%>%arrange(desc(abs(delta_mean_A4_minus_other)),desc(neglog10_fdr),.by_group=TRUE)%>%slice(1)%>%ungroup(); if(nrow(x)==0)return(x); if(dir=="A4-up")arrange(x,desc(neglog10_fdr),desc(delta_mean_A4_minus_other))%>%slice_head(n=4) else arrange(x,desc(neglog10_fdr),delta_mean_A4_minus_other)%>%slice_head(n=4)}
plot_one=function(rt){d=filter(df,regulon_type==rt); labs=bind_rows(pick(d,"Human","A4-up"),pick(d,"Human","Other-up"),pick(d,"Mouse","A4-up"),pick(d,"Mouse","Other-up"))%>%distinct(species,TF_upper,.keep_all=TRUE); e=d%>%filter(TF_upper=="EGR1")%>%group_by(species,TF_upper)%>%arrange(desc(delta_mean_A4_minus_other),desc(neglog10_fdr),.by_group=TRUE)%>%slice(1)%>%ungroup(); regular=filter(labs,TF_upper!="EGR1")
p=ggplot(d,aes(delta_mean_A4_minus_other,neglog10_fdr))+geom_hline(yintercept=-log10(.05),linetype="dashed",color="grey60",linewidth=.35)+geom_vline(xintercept=0,linetype="dashed",color="grey45",linewidth=.45)+geom_point(data=filter(d,!is_EGR1),aes(color=direction_group),size=2,alpha=.75)+geom_point(data=filter(d,is_EGR1),aes(color=direction_group),size=5.2,alpha=.98)+geom_point(data=filter(d,is_EGR1),shape=21,fill=NA,color="black",size=6,stroke=.55)+scale_color_manual(values=c("A4-up"="#E64B35","NS"="grey75","Other-up"="#3C6FB6"))+scale_y_continuous(limits=c(0,345),breaks=c(0,100,200,300),expand=expansion(mult=c(.02,.06)))+facet_wrap(~species,nrow=1,scales="free_x")+coord_cartesian(clip="off")+theme_classic(base_family="Arial",base_size=14)+theme(legend.position="top",plot.title=element_text(size=22,face="bold",hjust=.5),axis.title=element_text(size=19),axis.text=element_text(size=14),strip.background=element_rect(fill="grey92",color="grey65"),strip.text=element_text(size=15,face="bold"))+labs(title=ifelse(rt=="core","Core regulon activity differences in A4-OLs","Extended regulon activity differences in A4-OLs"),x="Mean AUC difference: A4-OLs - Other OLs",y="-log10(FDR)")
if(nrow(regular)>0)p=p+geom_text_repel(data=regular,aes(label=TF_show),family="Arial",size=3.8,max.overlaps=Inf,box.padding=.6,point.padding=.35,seed=123)
if(nrow(e)>0)p=p+geom_text_repel(data=e,aes(label=TF_show),family="Arial",size=4.5,fontface="bold",max.overlaps=Inf,box.padding=.8,point.padding=.5,seed=321)
ggsave(file.path(PLOT,paste0("Fig9_",rt,"_human_mouse_regulon_activity_volcano_top4_EGR1_highlight.png")),p,width=13.2,height=7,dpi=300,bg="white"); ggsave(file.path(PLOT,paste0("Fig9_",rt,"_human_mouse_regulon_activity_volcano_top4_EGR1_highlight.pdf")),p,width=13.2,height=7,bg="white")}
plot_one("core"); plot_one("extended")
